### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by itsbhanusharma** [jrenton/volumio#3]
Hi!
I was seeking a way to install this to my raspberry pi 2 so that i may tinker and help you testing and further developing this build maybe it helps find more bugs soon...

Can You Please post detailed instructions on installation and setup and Known bugs?

I'd be Glad to contribute in fixing as much bugs as possible up to my knowledge.

Regads
Bhanu.

**Comment by judocode** [comment]
Hi! 

Thanks for your interest in the project. Right now I am still hashing out details, but soon I will offer an IMG file with documentation. I will keep you informed!

**Comment by itsbhanusharma** [comment]
Also, i Just wanted to discuss the Possibility it can be built around using latest versions of debian and all the packages involved. (original volumio breaks as we update it).
It's kinda strange as the machine gets restricted to audio playback whereas i plan to add at least a UPS control functionality to it (apcupsd) 

as this is being built from scratch, i am just asking for the scope of possibilities.  Let me know if i can be a help with anything. :)

**Comment by itsbhanusharma** [comment]
Project seems dead
